/* Curated Apple-style emoji set for the desktop emoji picker.
   Format: [grupo, unified, caractere, palavras-chave].
   PNGs (Apple 64px) live in ./emoji/<unified>.png — baixados de emoji-datasource-apple. */
window.EMOJI_DATA = [
["Rostos","1f600","😀","sorriso feliz grinar"],
["Rostos","1f603","😃","sorriso feliz boca aberta"],
["Rostos","1f604","😄","feliz olhos sorrindo"],
["Rostos","1f601","😁","grinar radiante feliz"],
["Rostos","1f606","😆","rindo apertado feliz"],
["Rostos","1f605","😅","rindo suor alivio"],
["Rostos","1f923","🤣","rolando de rir chao"],
["Rostos","1f602","😂","chorando de rir lagrimas"],
["Rostos","1f642","🙂","sorriso leve"],
["Rostos","1f643","🙃","de cabeca para baixo ironia"],
["Rostos","1f609","😉","piscadela"],
["Rostos","1f60a","😊","sorriso timido corar feliz"],
["Rostos","1f607","😇","anjo auréola inocente"],
["Rostos","1f970","🥰","apaixonado coracoes amor"],
["Rostos","1f60d","😍","olhos de coracao amor"],
["Rostos","1f929","🤩","estrelas deslumbrado uau"],
["Rostos","1f618","😘","beijo coracao"],
["Rostos","1f617","😗","beijinho"],
["Rostos","1f60b","😋","delicia lambendo gostoso"],
["Rostos","1f61b","😛","lingua de fora"],
["Rostos","1f61c","😜","lingua piscadela brincadeira"],
["Rostos","1f92a","🤪","maluco doido"],
["Rostos","1f911","🤑","dinheiro cifrao rico"],
["Rostos","1f917","🤗","abraco"],
["Rostos","1f92d","🤭","risadinha mao na boca"],
["Rostos","1f92b","🤫","silencio shhh"],
["Rostos","1f914","🤔","pensativo pensando duvida"],
["Rostos","1f928","🤨","sobrancelha erguida desconfianca"],
["Rostos","1f610","😐","neutro serio"],
["Rostos","1f611","😑","sem expressao inexpressivo"],
["Rostos","1f636","😶","sem boca calado"],
["Rostos","1f60f","😏","sorriso maroto"],
["Rostos","1f612","😒","sem graca contrariado"],
["Rostos","1f644","🙄","revirar os olhos"],
["Rostos","1f62c","😬","careta constrangido"],
["Rostos","1f60c","😌","aliviado tranquilo"],
["Rostos","1f614","😔","pensativo triste cabisbaixo"],
["Rostos","1f634","😴","dormindo sono"],
["Rostos","1f637","😷","mascara doente"],
["Rostos","1f912","🤒","febre termometro doente"],
["Rostos","1f922","🤢","enjoado nausea"],
["Rostos","1f92e","🤮","vomitando"],
["Rostos","1f927","🤧","espirro gripe"],
["Rostos","1f975","🥵","calor suando quente"],
["Rostos","1f976","🥶","frio congelando"],
["Rostos","1f635","😵","tonto atordoado"],
["Rostos","1f92f","🤯","explodindo cabeca chocado"],
["Rostos","1f920","🤠","caubói chapéu"],
["Rostos","1f973","🥳","festa comemoracao aniversario"],
["Rostos","1f60e","😎","óculos de sol estiloso"],
["Rostos","1f913","🤓","nerd óculos"],
["Rostos","1f9d0","🧐","monóculo analisando"],
["Rostos","1f615","😕","confuso incerto"],
["Rostos","1f61f","😟","preocupado"],
["Rostos","1f641","🙁","descontente triste leve"],
["Rostos","1f62e","😮","surpreso boca aberta"],
["Rostos","1f632","😲","pasmo espantado"],
["Rostos","1f633","😳","corado envergonhado"],
["Rostos","1f97a","🥺","olhos pidão suplicante"],
["Rostos","1f628","😨","assustado medo"],
["Rostos","1f630","😰","ansioso suor medo"],
["Rostos","1f625","😥","triste aliviado decepcao"],
["Rostos","1f622","😢","chorando lagrima triste"],
["Rostos","1f62d","😭","chorando muito choro"],
["Rostos","1f631","😱","gritando de medo pavor"],
["Rostos","1f616","😖","confuso frustrado"],
["Rostos","1f61e","😞","decepcionado"],
["Rostos","1f613","😓","suor frio cansado"],
["Rostos","1f629","😩","exausto cansado"],
["Rostos","1f62b","😫","cansado estressado"],
["Rostos","1f624","😤","bufando irritado orgulho"],
["Rostos","1f621","😡","bravo furioso vermelho"],
["Rostos","1f620","😠","com raiva zangado"],
["Rostos","1f92c","🤬","xingando palavrão raiva"],
["Rostos","1f608","😈","diabo travesso sorrindo"],
["Rostos","1f47f","👿","diabo bravo"],
["Rostos","1f480","💀","caveira morte"],
["Rostos","1f4a9","💩","cocô"],
["Rostos","1f921","🤡","palhaço"],
["Rostos","1f47b","👻","fantasma"],
["Rostos","1f47d","👽","alienígena et"],
["Rostos","1f916","🤖","robô"],
["Rostos","1f383","🎃","abóbora halloween"],
["Gestos","1f44d","👍","joinha positivo curtir like"],
["Gestos","1f44e","👎","negativo descurtir dislike"],
["Gestos","1f44a","👊","soco punho"],
["Gestos","270a","✊","punho erguido força"],
["Gestos","1f91b","🤛","soco esquerda"],
["Gestos","1f91c","🤜","soco direita"],
["Gestos","1f44f","👏","palmas aplauso"],
["Gestos","1f64c","🙌","maos ao alto comemorar"],
["Gestos","1f450","👐","maos abertas"],
["Gestos","1f932","🤲","maos concha pedido"],
["Gestos","1f91d","🤝","aperto de mao acordo"],
["Gestos","1f64f","🙏","reza obrigado por favor"],
["Gestos","270d-fe0f","✍️","escrevendo mao"],
["Gestos","1f4aa","💪","musculo forca biceps"],
["Gestos","1f440","👀","olhos olhando"],
["Gestos","1f9e0","🧠","cerebro"],
["Gestos","1f44b","👋","tchau acenar ola"],
["Gestos","270b","✋","mao levantada pare"],
["Gestos","1f596","🖖","saudação vulcano"],
["Gestos","1f44c","👌","ok joia"],
["Gestos","1f90f","🤏","pouquinho pinça"],
["Gestos","270c-fe0f","✌️","paz e amor vitoria"],
["Gestos","1f91e","🤞","dedos cruzados sorte"],
["Gestos","1f91f","🤟","te amo mao"],
["Gestos","1f918","🤘","rock chifrinho"],
["Gestos","1f919","🤙","me liga shaka"],
["Gestos","1f448","👈","apontar esquerda"],
["Gestos","1f449","👉","apontar direita"],
["Gestos","1f446","👆","apontar cima"],
["Gestos","1f447","👇","apontar baixo"],
["Gestos","261d-fe0f","☝️","dedo indicador cima"],
["Pessoas","1f476","👶","bebê"],
["Pessoas","1f9d2","🧒","criança"],
["Pessoas","1f466","👦","menino"],
["Pessoas","1f467","👧","menina"],
["Pessoas","1f9d1","🧑","pessoa adulto"],
["Pessoas","1f468","👨","homem"],
["Pessoas","1f469","👩","mulher"],
["Pessoas","1f474","👴","idoso velho"],
["Pessoas","1f475","👵","idosa velha"],
["Pessoas","1f46e","👮","policial"],
["Pessoas","1f477","👷","operário construção"],
["Pessoas","1f482","💂","guarda"],
["Pessoas","1f575-fe0f","🕵️","detetive investigador"],
["Pessoas","1f478","👸","princesa"],
["Pessoas","1f934","🤴","príncipe"],
["Pessoas","1f385","🎅","papai noel"],
["Pessoas","1f936","🤶","mamãe noel"],
["Pessoas","1f9b8","🦸","super-herói"],
["Pessoas","1f9b9","🦹","vilão"],
["Pessoas","1f9d9","🧙","mago bruxo"],
["Pessoas","1f647","🙇","reverência desculpa"],
["Pessoas","1f926","🤦","mão no rosto facepalm"],
["Pessoas","1f937","🤷","ombros dar de ombros sei lá"],
["Pessoas","1f483","💃","dançarina samba"],
["Pessoas","1f57a","🕺","dançarino"],
["Pessoas","1f6b6","🚶","pedestre andando"],
["Pessoas","1f3c3","🏃","correndo"],
["Natureza","1f436","🐶","cachorro cão"],
["Natureza","1f431","🐱","gato"],
["Natureza","1f42d","🐭","rato camundongo"],
["Natureza","1f430","🐰","coelho"],
["Natureza","1f98a","🦊","raposa"],
["Natureza","1f43b","🐻","urso"],
["Natureza","1f43c","🐼","panda"],
["Natureza","1f428","🐨","coala"],
["Natureza","1f42f","🐯","tigre"],
["Natureza","1f981","🦁","leão"],
["Natureza","1f42e","🐮","vaca boi"],
["Natureza","1f437","🐷","porco"],
["Natureza","1f438","🐸","sapo"],
["Natureza","1f435","🐵","macaco"],
["Natureza","1f648","🙈","macaco não vejo"],
["Natureza","1f649","🙉","macaco não ouço"],
["Natureza","1f64a","🙊","macaco não falo"],
["Natureza","1f414","🐔","galinha"],
["Natureza","1f427","🐧","pinguim"],
["Natureza","1f426","🐦","pássaro"],
["Natureza","1f989","🦉","coruja"],
["Natureza","1f43a","🐺","lobo"],
["Natureza","1f434","🐴","cavalo"],
["Natureza","1f984","🦄","unicórnio"],
["Natureza","1f41d","🐝","abelha"],
["Natureza","1f98b","🦋","borboleta"],
["Natureza","1f41e","🐞","joaninha"],
["Natureza","1f422","🐢","tartaruga"],
["Natureza","1f40d","🐍","cobra"],
["Natureza","1f419","🐙","polvo"],
["Natureza","1f420","🐠","peixe tropical"],
["Natureza","1f42c","🐬","golfinho"],
["Natureza","1f988","🦈","tubarão"],
["Natureza","1f433","🐳","baleia"],
["Natureza","1f418","🐘","elefante"],
["Natureza","1f992","🦒","girafa"],
["Natureza","1f415","🐕","cachorro"],
["Natureza","1f408","🐈","gato"],
["Natureza","1f331","🌱","muda broto planta"],
["Natureza","1f333","🌳","árvore"],
["Natureza","1f334","🌴","palmeira coqueiro"],
["Natureza","1f335","🌵","cacto"],
["Natureza","1f340","🍀","trevo sorte"],
["Natureza","1f33f","🌿","erva folhagem"],
["Natureza","1f341","🍁","folha bordo outono"],
["Natureza","1f337","🌷","tulipa"],
["Natureza","1f339","🌹","rosa"],
["Natureza","1f33a","🌺","hibisco flor"],
["Natureza","1f33b","🌻","girassol"],
["Natureza","1f338","🌸","flor de cerejeira"],
["Natureza","1f31e","🌞","sol rosto"],
["Natureza","1f319","🌙","lua"],
["Natureza","2b50","⭐","estrela"],
["Natureza","1f31f","🌟","estrela brilhante"],
["Natureza","26a1","⚡","raio energia"],
["Natureza","1f525","🔥","fogo chama"],
["Natureza","1f4a5","💥","explosão colisão"],
["Natureza","2601-fe0f","☁️","nuvem"],
["Natureza","26c5","⛅","sol entre nuvens"],
["Natureza","2744-fe0f","❄️","floco de neve frio"],
["Natureza","1f308","🌈","arco-íris"],
["Natureza","1f4a7","💧","gota água"],
["Natureza","1f30a","🌊","onda mar"],
["Comida","1f34e","🍎","maçã"],
["Comida","1f34c","🍌","banana"],
["Comida","1f349","🍉","melancia"],
["Comida","1f347","🍇","uva"],
["Comida","1f353","🍓","morango"],
["Comida","1f352","🍒","cereja"],
["Comida","1f351","🍑","pêssego"],
["Comida","1f34d","🍍","abacaxi"],
["Comida","1f345","🍅","tomate"],
["Comida","1f965","🥥","coco"],
["Comida","1f951","🥑","abacate"],
["Comida","1f346","🍆","berinjela"],
["Comida","1f955","🥕","cenoura"],
["Comida","1f33d","🌽","milho"],
["Comida","1f336-fe0f","🌶️","pimenta"],
["Comida","1f954","🥔","batata"],
["Comida","1f35e","🍞","pão"],
["Comida","1f950","🥐","croissant"],
["Comida","1f9c0","🧀","queijo"],
["Comida","1f95a","🥚","ovo"],
["Comida","1f373","🍳","ovo frito"],
["Comida","1f95e","🥞","panqueca"],
["Comida","1f953","🥓","bacon"],
["Comida","1f354","🍔","hambúrguer"],
["Comida","1f35f","🍟","batata frita"],
["Comida","1f355","🍕","pizza"],
["Comida","1f32d","🌭","cachorro-quente"],
["Comida","1f96a","🥪","sanduíche"],
["Comida","1f32e","🌮","taco"],
["Comida","1f32f","🌯","burrito"],
["Comida","1f372","🍲","panela sopa comida"],
["Comida","1f957","🥗","salada"],
["Comida","1f37f","🍿","pipoca"],
["Comida","1f35c","🍜","lámen macarrão"],
["Comida","1f363","🍣","sushi"],
["Comida","1f364","🍤","camarão frito"],
["Comida","1f366","🍦","sorvete casquinha"],
["Comida","1f369","🍩","rosquinha donut"],
["Comida","1f36a","🍪","biscoito cookie"],
["Comida","1f382","🎂","bolo aniversário"],
["Comida","1f370","🍰","fatia de bolo"],
["Comida","1f9c1","🧁","cupcake"],
["Comida","1f36b","🍫","chocolate"],
["Comida","1f36d","🍭","pirulito"],
["Comida","1f37c","🍼","mamadeira"],
["Comida","1f95b","🥛","leite copo"],
["Comida","2615","☕","café"],
["Comida","1f9c9","🧉","chimarrão tereré"],
["Comida","1f37e","🍾","champanhe espumante"],
["Comida","1f377","🍷","vinho taça"],
["Comida","1f37a","🍺","cerveja chopp"],
["Comida","1f37b","🍻","cervejas brinde"],
["Comida","1f942","🥂","brinde taças"],
["Comida","1f964","🥤","copo canudo refrigerante"],
["Viagem","1f697","🚗","carro"],
["Viagem","1f695","🚕","táxi"],
["Viagem","1f699","🚙","suv jipe"],
["Viagem","1f68c","🚌","ônibus"],
["Viagem","1f693","🚓","viatura polícia"],
["Viagem","1f691","🚑","ambulância"],
["Viagem","1f692","🚒","bombeiro caminhão"],
["Viagem","1f69a","🚚","caminhão"],
["Viagem","1f69c","🚜","trator"],
["Viagem","1f6b2","🚲","bicicleta"],
["Viagem","1f3cd-fe0f","🏍️","moto"],
["Viagem","2708-fe0f","✈️","avião"],
["Viagem","1f680","🚀","foguete"],
["Viagem","1f681","🚁","helicóptero"],
["Viagem","26f5","⛵","veleiro barco"],
["Viagem","1f6a2","🚢","navio"],
["Viagem","1f682","🚂","trem locomotiva"],
["Viagem","1f3e0","🏠","casa"],
["Viagem","1f3e2","🏢","prédio escritório"],
["Viagem","1f3e5","🏥","hospital"],
["Viagem","1f3e6","🏦","banco"],
["Viagem","1f3eb","🏫","escola"],
["Viagem","26ea","⛪","igreja"],
["Viagem","1f5fd","🗽","estátua da liberdade"],
["Viagem","1f30b","🌋","vulcão"],
["Viagem","1f3d6-fe0f","🏖️","praia"],
["Viagem","1f307","🌇","pôr do sol cidade"],
["Viagem","1f309","🌉","ponte noite"],
["Viagem","1f388","🎈","balão bexiga"],
["Viagem","1f386","🎆","fogos de artifício"],
["Objetos","1f4f1","📱","celular smartphone"],
["Objetos","1f4bb","💻","notebook laptop"],
["Objetos","1f5a5-fe0f","🖥️","computador monitor"],
["Objetos","1f4f7","📷","câmera foto"],
["Objetos","1f4f9","📹","filmadora vídeo"],
["Objetos","1f3a5","🎥","câmera de cinema"],
["Objetos","1f4fa","📺","televisão tv"],
["Objetos","1f4fb","📻","rádio"],
["Objetos","1f50b","🔋","bateria"],
["Objetos","1f4a1","💡","lâmpada ideia"],
["Objetos","1f526","🔦","lanterna"],
["Objetos","1f4da","📚","livros"],
["Objetos","1f4dd","📝","anotação memo escrever"],
["Objetos","270f-fe0f","✏️","lápis"],
["Objetos","1f4cc","📌","tachinha pin"],
["Objetos","1f4ce","📎","clipe de papel"],
["Objetos","2702-fe0f","✂️","tesoura"],
["Objetos","1f4cf","📏","régua"],
["Objetos","1f512","🔒","cadeado fechado"],
["Objetos","1f513","🔓","cadeado aberto"],
["Objetos","1f511","🔑","chave"],
["Objetos","1f528","🔨","martelo"],
["Objetos","1f527","🔧","chave de boca ferramenta"],
["Objetos","2699-fe0f","⚙️","engrenagem configuração"],
["Objetos","1f4a3","💣","bomba"],
["Objetos","1f489","💉","seringa injeção vacina"],
["Objetos","1f48a","💊","remédio pílula"],
["Objetos","1f6d2","🛒","carrinho compras"],
["Objetos","1f381","🎁","presente"],
["Objetos","1f3af","🎯","alvo dardo"],
["Objetos","1f3b2","🎲","dado"],
["Objetos","1f9e9","🧩","quebra-cabeça peça"],
["Objetos","1f4b0","💰","saco de dinheiro"],
["Objetos","1f4b3","💳","cartão de crédito"],
["Objetos","1f48e","💎","diamante joia"],
["Objetos","1f4e2","📢","megafone anúncio"],
["Objetos","1f514","🔔","sino notificação"],
["Objetos","1f3b5","🎵","nota musical música"],
["Objetos","1f3a4","🎤","microfone"],
["Objetos","1f3a7","🎧","fone de ouvido"],
["Objetos","1f3b8","🎸","guitarra violão"],
["Objetos","1f3b9","🎹","piano teclado"],
["Objetos","1f941","🥁","bateria tambor"],
["Objetos","23f0","⏰","despertador alarme"],
["Objetos","231a","⌚","relógio de pulso"],
["Objetos","1f4c5","📅","calendário"],
["Objetos","1f4ca","📊","gráfico barras"],
["Objetos","1f4c8","📈","gráfico subindo alta"],
["Objetos","1f4c9","📉","gráfico caindo queda"],
["Símbolos","2764-fe0f","❤️","coração vermelho amor"],
["Símbolos","1f9e1","🧡","coração laranja"],
["Símbolos","1f49b","💛","coração amarelo"],
["Símbolos","1f49a","💚","coração verde"],
["Símbolos","1f499","💙","coração azul"],
["Símbolos","1f49c","💜","coração roxo"],
["Símbolos","1f5a4","🖤","coração preto"],
["Símbolos","1f90d","🤍","coração branco"],
["Símbolos","1f494","💔","coração partido"],
["Símbolos","1f495","💕","dois corações"],
["Símbolos","1f496","💖","coração brilhante"],
["Símbolos","1f497","💗","coração crescendo"],
["Símbolos","1f498","💘","coração flecha cupido"],
["Símbolos","2728","✨","brilhos faíscas"],
["Símbolos","1f4ab","💫","tontura estrela"],
["Símbolos","1f4a4","💤","zzz sono"],
["Símbolos","2705","✅","check certo verde"],
["Símbolos","274c","❌","x erro errado"],
["Símbolos","2b55","⭕","círculo vermelho"],
["Símbolos","2757","❗","exclamação"],
["Símbolos","2753","❓","interrogação"],
["Símbolos","26a0-fe0f","⚠️","atenção aviso perigo"],
["Símbolos","1f6ab","🚫","proibido"],
["Símbolos","1f4a2","💢","irritação raiva símbolo"],
["Símbolos","1f4ac","💬","balão de fala"],
["Símbolos","1f4ad","💭","balão de pensamento"],
["Símbolos","1f195","🆕","novo new"],
["Símbolos","1f193","🆓","grátis free"],
["Símbolos","2b06-fe0f","⬆️","seta cima"],
["Símbolos","2b07-fe0f","⬇️","seta baixo"],
["Símbolos","27a1-fe0f","➡️","seta direita"],
["Símbolos","2b05-fe0f","⬅️","seta esquerda"],
["Símbolos","1f504","🔄","recarregar repetir"],
["Símbolos","25b6-fe0f","▶️","play"],
["Símbolos","23f8-fe0f","⏸️","pausa"],
["Símbolos","2795","➕","mais adicionar"],
["Símbolos","267b-fe0f","♻️","reciclagem"],
["Símbolos","1f4af","💯","cem nota máxima"],
["Símbolos","1f51d","🔝","topo top"],
["Bandeiras","1f1e7-1f1f7","🇧🇷","brasil"],
["Bandeiras","1f3c1","🏁","bandeira quadriculada chegada"],
["Bandeiras","1f6a9","🚩","bandeira triangular"],
["Bandeiras","1f3f4","🏴","bandeira preta"],
["Bandeiras","1f3f3-fe0f","🏳️","bandeira branca"],
["Bandeiras","1f1fa-1f1f8","🇺🇸","estados unidos eua"],
["Bandeiras","1f1f5-1f1f9","🇵🇹","portugal"],
["Bandeiras","1f1e6-1f1f7","🇦🇷","argentina"],
["Bandeiras","1f1ea-1f1f8","🇪🇸","espanha"],
["Bandeiras","1f1eb-1f1f7","🇫🇷","frança"],
["Bandeiras","1f1ee-1f1f9","🇮🇹","itália"],
["Bandeiras","1f1e9-1f1ea","🇩🇪","alemanha"],
["Bandeiras","1f1ec-1f1e7","🇬🇧","reino unido inglaterra"],
["Bandeiras","1f1ef-1f1f5","🇯🇵","japão"]
];
